### ISSUE TITLE
Possible default component with all styles applied?

### ISSUE THREAD

**Issue by dottjt** [jxnblk/styled-system#333] opened 2018-11-02 19:44 UTC
Perhaps I'm missing something, however is there currently a helper function that applies every single possible style prop to a styled-component/system-compoent? Just because I've noticed Rebass components don't seem to include all props, so I'm constantly having to add styled-system props to components. 

Or perhaps I'm missing something?

**Comment by jxnblk** [comment] 2018-11-04 15:42
Duplicate of #168

**Closed by jxnblk** 2018-11-04 15:42 UTC
